name: 'Hello World Spring Boot App CICD'
description: 'build with maven, sync to ec2, and deploy .jar'
inputs:
  USERNAME:
    required: true
  PUBLIC_IP:
    required: true
  SSH_KEY:
    required: true

runs: using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - name: Sync files to ec2 
      env:
        dest: '${{ inputs.USERNAME }}@${{ inputs.PUBLIC_IP }}:/srv/hello_world/'
      run: |
        echo "${{ inputs.SSH_KEY }}" >> deploy_key
        chmod 600 ./deploy_key
        ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no ${{ inputs.USERNAME }}@${{ inputs.PUBLIC_IP }}        
        rsync -charlvzi --delete \
          -e 'ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no' \
          --exclude '/deploy_key' \
          --exclude '/.*/' \
          --exclude '.*' \
          --exclude '/cgi-bin/' \
          --exclude 'README.md' \
          ./ ${{env.dest}}
          
    - name: SSH into EC2 and Run Commands towards running jar file
      env:
        SSH_PRIVATE_KEY: ${{ inputs.SSH_KEY }}
        SSH_USERNAME: ${{ inputs.USERNAME }}
        EC2_PUBLIC_IP: ${{ inputs.PUBLIC_IP }}
      run: |
        ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no ${SSH_USERNAME}@${EC2_PUBLIC_IP} << 'EOF'
          # Kill processes using port 8080
          sudo kill -9 $(sudo lsof -t -i:8080)

          # Run .jar file in the background
          cd /srv/hello_world/target/
          nohup java -jar demo-0.0.1-SNAPSHOT.jar &
        EOF
